<?php 
namespace skyss0fly\AutoStop;

use pocketmine\plugin\PluginBase;
use DateTime;

class Main extends PluginBase {

public function onLoad(): void {
$this->saveDefaultConfig();
$cfg = $this->getConfig();



}
}
